version: "3"
services:
  clemonarte_frontend:
    build:
      context: .
    container_name: clemonarte_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - traefik_network
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_PORT=${FRONTEND_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.clemonarte_frontend.entrypoints=web,websecure"
      - "traefik.http.routers.clemonarte_frontend.rule=Host(`${CLEMONARTE_FRONTEND_URL}`)"
      - "traefik.http.services.clemonarte_frontend.loadbalancer.server.port=${FRONTEND_PORT}"
      - "traefik.http.routers.clemonarte_frontend.tls=true"
      - "traefik.http.routers.clemonarte_frontend.tls.certresolver=leresolver"

networks:
  traefik_network:
    external: true
