version: '3'
services:
  todo_frontend:
    build:
      context: .
    container_name: todo_frontend
    restart: unless-stopped
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.todo_frontend.entrypoints=web,websecure"
      - "traefik.http.routers.todo_frontend.rule=Host(`${TODO_FRONTEND_URL}`)"
      - "traefik.http.services.todo_frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.todo_frontend.tls=true"
      - "traefik.http.routers.todo_frontend.tls.certresolver=leresolver"

networks:
  traefik_network:
    external: true
