name: Deploy
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: launch Docker-compose
        uses: appleboy/ssh-action@master
        env:
          CLEMONARTE_FRONTEND_URL: ${{ vars.CLEMONARTE_FRONTEND_URL }}
          BACKEND_URL: ${{ vars.BACKEND_URL }}
          PORT: ${{ vars.PORT }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          envs: CLEMONARTE_FRONTEND_URL, BACKEND_URL, PORT
          script: |
            echo "CLEMONARTE_FRONTEND_URL : $CLEMONARTE_FRONTEND_URL"
            echo "BACKEND_URL : $BACKEND_URL"
            echo "PORT : $PORT"
            pwd
            if [ ! -d "./Clemonarte-frontend" ]
            then
              git clone git@github.com:VincentBergerault/Clemonarte-frontend.git
            fi
            cd Clemonarte-frontend
            git pull origin main
            docker-compose up -d --build --force-recreate
