name: Deploy
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: launch Docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: | 
            pwd
            if [ ! -d "./Clemonarte" ]
            then
              git clone git@github.com:VincentBergerault/Clemonarte.git
            fi
            cd Clemonarte
            git pull origin main
            docker-compose up -d --build --force-recreate