name: Deploy
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: launch Docker-compose
        uses: appleboy/ssh-action@master
        env:
          BACKEND_URL: ${{ env.BACKEND_URL }}
          CLEMONARTE_FRONTEND_URL: ${{ env.CLEMONARTE_FRONTEND_URL }}
          FRONTEND_PORT: ${{ env.FRONTEND_PORT }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pwd
            if [ ! -d "./Clemonarte-frontend" ]
            then
              git clone git@github.com:VincentBergerault/Clemonarte-frontend.git
            fi
            cd Clemonarte-frontend
            git pull origin main
            docker-compose up -d --build --force-recreate
